[package]
name = "adfUtils"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = "0.31"
egui = "0.31"
rfd = "0.12"
tokio = { version = "1", features = ["full"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
confy = "0.5"
log = "0.4"
simplelog = "0.12"
raw-window-handle = "0.6"
